# Info about cloud where ECCD is installed
openstack_auth_url:
openstack_user:
openstack_password:
openstack_project_name:

# If no cloud info provided - director IP address is mandatory
director_ip: '10.137.89.100'
              
domain_name: 'n293-vpod5-prod344.sero.gic.ericsson.se'
container_registry_custom_user_id: admin
container_registry_custom_pw: nebula123

bro_size: '60Gi'
registry_size: '100Gi'

esa_lb: '10.137.89.187'
load_balancer_ip: '10.137.89.186'

syslog_ip: '10.216.249.114'
syslog_port: 6514

snmp_server_ip: '10.232.14.60'
snmp_community: 'public'

director_user: 'eccd'

is_collocated_env: True

#DDP data in site values
account:
ddpid:
enabled:
password:
