# The director IP must be in config for the NFVI environments
director_ip: 214.7.254.21

# Info about subsystems to be integrated
ENMs:
  - "ieatenmc7b16-5.athtem.eei.ericsson.se"

# Info about cloud where ECCD is installed
openstack_auth_url: ''
openstack_user: ''
openstack_password: ''
openstack_project_name: ''
# The following container registry related fields must be in config for the NFVI environments
container_registry_custom_user_id: admin
container_registry_custom_pw: nebula123

####################################################################
# Site values
iam_hostname: 'iam.n103-oss16043.seli.gic.ericsson.se'
vnfm_hostname: 'evnfm.n103-oss16043.seli.gic.ericsson.se'
gas_hostname: 'gas.n103-oss16043.seli.gic.ericsson.se'

docker_registry_hostname: 'reg-evnfm.n103-oss16043.seli.gic.ericsson.se'
helm_registry_hostname: 'helm.n103-oss16043.seli.gic.ericsson.se'
enable_smallstack: false

registry_size: '40Gi'
bro_size: '60Gi'

syslog_ip: '2001:1b70:82a7:1779::116'
syslog_port: 6514

snmp_server_ip: '2001:1b70:6209:17::61'
snmp_community: 'public'

load_balancer_ip: '2001:1b70:8209:60b0::2'
enm_load_balancer_ip: '2001:1b70:8209:60b0::3'

storage_class: 'network-file'

enm_scripting_cluster_ip: '2001:1b70:82b9:0224:0000:0000:1016:001e'
enm_notification_ip: '2001:1b70:82b9:0224:0000:0000:1016:0020'
enm_username: 'administrator'
enm_password: 'TestPassw0rd'
enm_connection_timeout_in_milliseconds: '20000'
enm_scripting_ssh_port: '22'

is_collocated_env: True

director_user: eccd
