# Info about subsystems to be integrated
ENMs:
  - "ieatenmc4a08-8.athtem.eei.ericsson.se"

# Info about cloud where ECCD is installed
openstack_auth_url: 'https://cloud12a.athtem.eei.ericsson.se:13000/v3'
openstack_user: 'ORCH_PLM_HUBBLE_C12A5_admin'
openstack_password: 'admin123'
openstack_project_name: 'ORCH_PLM_HUBBLE_C12A5'

####################################################################
# Site values
iam_hostname: 'iam.ccd-c12a5.athtem.eei.ericsson.se'
vnfm_hostname: 'evnfm.ccd-c12a5.athtem.eei.ericsson.se'
gas_hostname: 'gas.ccd-c12a5.athtem.eei.ericsson.se'

docker_registry_hostname: 'registry.ccd-c12a5.athtem.eei.ericsson.se'
helm_registry_hostname: 'helm-registry.ccd-c12a5.athtem.eei.ericsson.se'
enable_smallstack: false

registry_size: '100Gi'
bro_size: '10Gi'

load_balancer_ip: '10.32.185.3'

enm_scripting_cluster_ip: '131.160.200.211'
enm_notification_ip: '131.160.200.213'
enm_username: 'administrator'
enm_password: 'TestPassw0rd'
enm_connection_timeout_in_milliseconds: '20000'
enm_scripting_ssh_port: '22'

director_user: eccd
