# General cloud information
openstack_auth_url: https://cloud11a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_RV_SMCCD_C11A2_admin
openstack_password: admin123
openstack_project_name: ORCH_RV_SMCCD_C11A2

# Cluster info
api_hostname: api.ccd-c11a2.athtem.eei.ericsson.se
registry_hostname: container.ccd-c11a2.athtem.eei.ericsson.se
registry_storage_size: 100Gi

# ECFE info
peer_address:
  - 10.150.132.4
  - 10.150.132.5
peer-asn: 4247257098
my-asn: 4247257108
address-pools:
  - 10.150.131.130-10.150.131.135

# Networks info
director_network: f939cfe6-b992-484d-9c44-aee968d3a421
director_subnet: 4e48c004-c6b4-41fb-aa6f-c4a03af2c3af
director_virtual_router_id: 90
worker_network: f939cfe6-b992-484d-9c44-aee968d3a421
worker_subnet: 4e48c004-c6b4-41fb-aa6f-c4a03af2c3af

# Public key for passwordless access
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEV0zhWNbXbuWUwpfVCgWPxz4hCidyyZXtIoZAlYej0CBeVtFF6XCDclx7Uu+GGXBGZwHn0gKKlZoxpvgLVLXibX3XYVmwkhpkoYz8gK9Aiopv/T+MWNVl9LZmDug0hkB4bAG2uMHNTSvboITzmR+Wpq1/SglW/W36xRf1/JzlvO45zl4LLpmslDDH3riv3AikyWglFuX4GvWzUgtMID+HBjUVr+M5zpZoKELC07lV73X8v4WuXS1eja+ticxuw/wtCrwI28IjhgLRfoMotpOUUB1Jwss0tsZNhzOxKGAMsK0Ccw4UF+tmNSZRCyLunggZXG5wMiC5/e47YuEkZTnh ansible-generated on ecm157x154.ete.ka.sw.ericsson.se
