# General cloud information
openstack_auth_url: https://cloud12a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_PLM_HUBBLE_C12A5_admin
openstack_password: admin123
openstack_project_name: ORCH_PLM_HUBBLE_C12A5

# Cluster info
api_hostname: api.ccd-c12a5.athtem.eei.ericsson.se
registry_hostname: k8s-registry.eccd.local
registry_storage_size: 100Gi

# ECFE info
peer_address:
  - 10.232.35.1
peer-asn: 64515
my-asn: 64520
address-pools:
  - 10.32.185.2-10.32.185.3
  - 10.32.185.17-10.32.185.17
  - 10.32.185.26-10.32.185.26

# Networks info
director_network: fd0bc65c-1ead-4cc4-9554-d33602a070d5
director_subnet: 73380de0-347d-404a-9136-3bf4bb65be8a
director_virtual_router_id: 125
worker_network: 6e719855-05a0-4682-ac50-2bb639ecb647
worker_subnet: 5d36a39b-2bdd-4b64-a836-172138c13aea

# Public key for passwordless access
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAf/ide4Djt7QNeuanjH0B+JUW9Jm+7OwHt22GFuDVd8Ib4HKm8hKWAmA/0TB/gcBy5a3GT35fmtuVmH6gRP7St4k4Wnv04Y9eGPEogeSoDhEVLaF/i2LYB2ZcoRJf7Iqhe86WftzsHR1ZYimdpE1JVuP+eHeSweNbVnPBaOKj6zK8CF6rA+odKCN0MMMTWalJYMU87/RtxQqBOjoTFFH3hUfBoxT8i9l9LK52RboBFq9wqfRYSGU79re81VuHESkZcKy0wQec5cB9sjfzIE55LVFiGcLzZUzikjzY27sVPR8dk3Gz2TExKtOXDgf2ex7DVJLGbLdlIs4WEppRjlBj Generated-by-Nova
