# General cloud information
openstack_auth_url: https://cloud11a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_RV_CCD_C11A022_admin
openstack_password: admin123
openstack_project_name: ORCH_RV_CCD_C11A022

# Cluster info
api_hostname: api.ccd-c11a022.athtem.eei.ericsson.se
registry_hostname: k8s-registry.eccd.local
registry_storage_size: 100Gi

# ECFE info
peer_address:
  - 10.150.66.4
peer-asn: 64515
my-asn: 64520
address-pools:
  - 10.32.187.86-10.32.187.86
  - 10.32.187.55-10.32.187.55
  - 10.32.187.58-10.32.187.62

# Networks info
director_network: 00608a3d-5410-441b-b15c-73139ac92f20
director_subnet: d5008277-c9cc-4673-85c9-d543830137a5
director_virtual_router_id: 90 
worker_network: 00608a3d-5410-441b-b15c-73139ac92f20
worker_subnet: d5008277-c9cc-4673-85c9-d543830137a5

# Public key for passwordless access
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD9ZouLg/aDbo1U9L2bPvalcWxzPnDdT06WqDZfyeZl5JK7a02PmjHMWP4t491E+tDztaxj0SCtfvTD0oCFIIDbf6TzgHVz0kSzbc7w/ehOcFB7HQU33UUOZb53+n703XHvQKHElJoCivypLFMogsC7Agb/h7R/6fgJBbVyxTZHSiihapfIEv63cW1fSuqk0uM9xsQFvCJeouDXtPQJTR0csBQWS8F6zggdwsQD+QZFQvjyBR26sUYWShN2FKyRyflIMKmvSas3kXPTh+/0xjXWHskjRg6w3u6nSpDGzZI+Vrl0I8GlV3sBXVYWqfx+O340ojxZfHfAgetDexjmo9Iv
