# General cloud information
openstack_auth_url: https://cloud5a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_RV_Huracan_C5A1_admin
openstack_password: admin123
openstack_project_name: ORCH_RV_Huracan_C5A1

# Cluster info
api_hostname: api.huracan-c5a1.athtem.eei.ericsson.se
registry_hostname: container.huracan-c5a1.athtem.eei.ericsson.se
registry_storage_size: 20Gi

# ECFE info
peer_address:
  - 10.232.40.1
peer-asn: 64515
my-asn: 64520
address-pools:
  - 10.210.214.28-10.210.214.31

# Networks info
director_network: cd5ab5a1-eaa1-4bdf-b590-d8eecbc34307
director_subnet: 9f6c2e08-9733-4e41-be45-38b1b15f9547
director_virtual_router_id: 50
worker_network: cecd62ba-add2-4b0b-8259-80b2ef075e62
worker_subnet: 99d4d816-6d76-4950-94cb-98e50b3bf2bf

# Public key for passwordless access
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEV0zhWNbXbuWUwpfVCgWPxz4hCidyyZXtIoZAlYej0CBeVtFF6XCDclx7Uu+GGXBGZwHn0gKKlZoxpvgLVLXibX3XYVmwkhpkoYz8gK9Aiopv/T+MWNVl9LZmDug0hkB4bAG2uMHNTSvboITzmR+Wpq1/SglW/W36xRf1/JzlvO45zl4LLpmslDDH3riv3AikyWglFuX4GvWzUgtMID+HBjUVr+M5zpZoKELC07lV73X8v4WuXS1eja+ticxuw/wtCrwI28IjhgLRfoMotpOUUB1Jwss0tsZNhzOxKGAMsK0Ccw4UF+tmNSZRCyLunggZXG5wMiC5/e47YuEkZTnh ansible-generated on ecm157x154.ete.ka.sw.ericsson.se
