# General cloud information
openstack_auth_url: https://cloud5a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_RV_Huracan_C5A1_admin
openstack_password: admin123
openstack_project_name: ORCH_RV_Huracan_C5A1

# Cluster info
api_hostname: api.huracan-c5a1.athtem.eei.ericsson.se
registry_hostname: container.huracan-c5a1.athtem.eei.ericsson.se
registry_storage_size: 100Gi

# ECFE info
peer_address:
  - 10.232.40.1
peer-asn: 64515
my-asn: 64520
address-pools:
  - 10.210.214.28-10.210.214.31

# Networks info
director_network: cd5ab5a1-eaa1-4bdf-b590-d8eecbc34307
director_subnet: 9f6c2e08-9733-4e41-be45-38b1b15f9547
director_virtual_router_id: 90
worker_network: cecd62ba-add2-4b0b-8259-80b2ef075e62
worker_subnet: 99d4d816-6d76-4950-94cb-98e50b3bf2bf

# Public key for passwordless access
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9TKcg6FFJBRDfY5A+D6s8BWxSk48bzZSaqbtCR/Apc+oqMSBmKHE4qEXu+mEGtfbpEkdDTISlasv/sDPfJxqbMHwUnwnMhlSnAkxR9Dcme1xZV7U04GBOBFhMcKBxfUbyzmlLH1tk6CBdJkndhb0XgKa/6hCS6au7tTjqsr9g2dWUGQQjR4LjQwt8m+XnHH2b5NNtRYVfpyH4V52i4xpAd4egbh6Y48pZM4yC4Cc621vhM+sETQhMBO0e7s6G0C2/JGT++P2kGHPRODUEh2iTkRF+U9N36bdGCTM54It4m5kld6oMTi/mlRWzXmfaA3AQW1bGiAA1rQ7Gx5EDXjRN root@atvts3430.athtem.eei.ericsson.se
