# General cloud information
openstack_auth_url: https://cloud15a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_DO_CCD_C15A011_admin
openstack_password: admin123
openstack_project_name: ORCH_DO_CCD_C15A011

# Cluster info
api_hostname: api.ccd-c15a011.athtem.eei.ericsson.se
registry_hostname: registry.ccd-c15a011.athtem.eei.ericsson.se
registry_storage_size: 30Gi

# ECFE info
peer_address:
  - 10.232.154.1
peer-asn: 64515
my-asn: 64520
address-pools:
  - 10.232.153.21-10.232.153.21
  - 10.232.153.111-10.232.153.113

# Networks info
director_network: 42cd84ca-4552-4d7b-a4c9-4d8cf22c0f48
director_subnet: acc80db8-f0c3-4ff8-bd28-5e83da88fd10
director_virtual_router_id: 120
worker_network: 42cd84ca-4552-4d7b-a4c9-4d8cf22c0f48
worker_subnet: acc80db8-f0c3-4ff8-bd28-5e83da88fd10

# Public key for passwordless access
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD9ZouLg/aDbo1U9L2bPvalcWxzPnDdT06WqDZfyeZl5JK7a02PmjHMWP4t491E+tDztaxj0SCtfvTD0oCFIIDbf6TzgHVz0kSzbc7w/ehOcFB7HQU33UUOZb53+n703XHvQKHElJoCivypLFMogsC7Agb/h7R/6fgJBbVyxTZHSiihapfIEv63cW1fSuqk0uM9xsQFvCJeouDXtPQJTR0csBQWS8F6zggdwsQD+QZFQvjyBR26sUYWShN2FKyRyflIMKmvSas3kXPTh+/0xjXWHskjRg6w3u6nSpDGzZI+Vrl0I8GlV3sBXVYWqfx+O340ojxZfHfAgetDexjmo9Iv Generated-by-Nova
