# General cloud information
openstack_auth_url: https://cloud12a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_RV_SMCCD_C12A4_admin
openstack_password: admin123
openstack_project_name: ORCH_RV_SMCCD_C12A4

# Cluster info
api_hostname: api.c12a4.athtem.eei.ericsson.se
registry_hostname: container.c12a4.athtem.eei.ericsson.se
registry_storage_size: 100Gi

# ECFE info
peer_address:
  - 10.232.35.4
  - 10.232.35.5
peer-asn: 4247257098
my-asn: 4247257108
address-pools:
  - 10.42.14.192-10.42.14.193

# Networks info
director_network: 8acdda7f-53e8-4e46-9ff5-1b89b84b96cf
director_subnet: 819d34a0-7b6f-461b-84bb-75b375c0b0db
director_virtual_router_id: 50
worker_network: 8acdda7f-53e8-4e46-9ff5-1b89b84b96cf
worker_subnet: 819d34a0-7b6f-461b-84bb-75b375c0b0db

# Public key for passwordless access
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEV0zhWNbXbuWUwpfVCgWPxz4hCidyyZXtIoZAlYej0CBeVtFF6XCDclx7Uu+GGXBGZwHn0gKKlZoxpvgLVLXibX3XYVmwkhpkoYz8gK9Aiopv/T+MWNVl9LZmDug0hkB4bAG2uMHNTSvboITzmR+Wpq1/SglW/W36xRf1/JzlvO45zl4LLpmslDDH3riv3AikyWglFuX4GvWzUgtMID+HBjUVr+M5zpZoKELC07lV73X8v4WuXS1eja+ticxuw/wtCrwI28IjhgLRfoMotpOUUB1Jwss0tsZNhzOxKGAMsK0Ccw4UF+tmNSZRCyLunggZXG5wMiC5/e47YuEkZTnh ansible-generated on ecm157x154.ete.ka.sw.ericsson.se
