# The director IP must be in config for the NFVI environments
director_ip: 214.6.2.40

# Info about cloud where ECCD is installed
openstack_auth_url: ''
openstack_user: ''
openstack_password: ''
openstack_project_name: ''

# The following container registry related fields must be in config for the NFVI environments
container_registry_custom_user_id: admin
container_registry_custom_pw: admin

####################################################################
# Site values
iam_hostname: 'iam-prod337.25108-prod337.flexilab.seli.gic.ericsson.se'
gas_hostname: 'gas-prod337.25108-prod337.flexilab.seli.gic.ericsson.se'
lm_hostname: 'eo-lm-prod337.25108-prod337.flexilab.seli.gic.ericsson.se'

registry_size: '10Gi'
load_balancer_ip: '214.6.0.242'

director_user: eccd

is_collocated_env: False
