# The director IP must be in config for the NFVI environments
director_ip: 10.150.140.103

# Info about cloud where ECCD is installed
openstack_auth_url: 'https://cloud15a.athtem.eei.ericsson.se/'
openstack_user: 'ORCH_PS_CCD_C15A006_admin'
openstack_password: 'admin123'
openstack_project_name: 'ORCH_PS_CCD_C15A006'

# The following container registry related fields must be in config for the NFVI environments
container_registry_custom_user_id: admin
container_registry_custom_pw: admin@123

####################################################################
# Site values
iam_hostname: 'iam-prod352.ccd-c15a006-prod352.athtem.eei.ericsson.se'
gas_hostname: 'gas-prod352.ccd-c15a006-prod352.athtem.eei.ericsson.se'
lm_hostname: 'eo-lm-prod352.ccd-c15a006-prod352.athtem.eei.ericsson.se'
git_hostname: 'git-prod352.ccd-c15a006-prod352.athtem.eei.ericsson.se'

registry_size: '10Gi'
load_balancer_ip: '10.150.139.168'

director_user: eccd

is_collocated_env: False
