# Openstack info
openstack_auth_url: https://cloud11a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_RV_SMCCD_C11A3_admin
openstack_password: admin123
openstack_project_name: ORCH_RV_SMCCD_C11A3
openstack_project_id: 7948abe05e8c491f977fdf1dc5e27b9d

# Cluster info
api_hostname: api.ccd-c11a3.athtem.eei.ericsson.se
registry_hostname: container.ccd-c11a3.athtem.eei.ericsson.se
registry_storage_size: 100Gi

# ECFE info
peer_address:
  - 10.150.66.4
  - 10.150.66.5
peer-asn: 4247257098
my-asn: 4247257108
address-pools:
  - 10.32.187.86-10.32.187.86
  - 10.32.187.55-10.32.187.55
  - 10.32.187.58-10.32.187.58
  - 10.32.187.59-10.32.187.59
  - 10.32.187.60-10.32.187.60
  - 10.32.187.61-10.32.187.61
  - 10.32.187.62-10.32.187.62



# Networks info
cp_network: p0-opstk-11-de-cni-ggn3
cp_subnet: p0-opstk-11-de-cni-ggn3_ipv4
worker_network: p0-opstk-11-de-cni-ggn3
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEV0zhWNbXbuWUwpfVCgWPxz4hCidyyZXtIoZAlYej0CBeVtFF6XCDclx7Uu+GGXBGZwHn0gKKlZoxpvgLVLXibX3XYVmwkhpkoYz8gK9Aiopv/T+MWNVl9LZmDug0hkB4bAG2uMHNTSvboITzmR+Wpq1/SglW/W36xRf1/JzlvO45zl4LLpmslDDH3riv3AikyWglFuX4GvWzUgtMID+HBjUVr+M5zpZoKELC07lV73X8v4WuXS1eja+ticxuw/wtCrwI28IjhgLRfoMotpOUUB1Jwss0tsZNhzOxKGAMsK0Ccw4UF+tmNSZRCyLunggZXG5wMiC5/e47YuEkZTnh ansible-generated on ecm157x154.ete.ka.sw.ericsson.se
