# Openstack info
openstack_auth_url: https://cloud13a.athtem.eei.ericsson.se:13000/v3
openstack_user: ORCH_VNF_C13A16_admin
openstack_password: admin123
openstack_project_name: ORCH_VNF_C13A16
openstack_project_id: b3ea73ecf546448fbcc825db3c2f31bc
# Cluster info
api_hostname: k8s-api.ccd2.athtem.eei.ericsson.se
registry_hostname: container.ccd2-c13a16.athtem.eei.ericsson.se
registry_storage_size: 100Gi
# ECFE info
peer_address:
  - 10.150.117.4
  - 10.150.117.5
peer-asn: 4247257098
my-asn: 4247257108
address-pools:
  - 10.150.116.36-10.150.116.39
# Networks info
cp_network: p121-opstk-13a-de-cni-ggn1
cp_subnet: p121-opstk-13a-de-cni-ggn1_ipv4
worker_network: p121-opstk-13a-de-cni-ggn1
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEV0zhWNbXbuWUwpfVCgWPxz4hCidyyZXtIoZAlYej0CBeVtFF6XCDclx7Uu+GGXBGZwHn0gKKlZoxpvgLVLXibX3XYVmwkhpkoYz8gK9Aiopv/T+MWNVl9LZmDug0hkB4bAG2uMHNTSvboITzmR+Wpq1/SglW/W36xRf1/JzlvO45zl4LLpmslDDH3riv3AikyWglFuX4GvWzUgtMID+HBjUVr+M5zpZoKELC07lV73X8v4WuXS1eja+ticxuw/wtCrwI28IjhgLRfoMotpOUUB1Jwss0tsZNhzOxKGAMsK0Ccw4UF+tmNSZRCyLunggZXG5wMiC5/e47YuEkZTnh ansible-generated on ecm157x154.ete.ka.sw.ericsson.se
